import React, { useCallback } from 'react'
import { Link } from 'react-router-dom'
import ToolLayout from '../components/ToolLayout.jsx'
import Converter from '../components/Converter.jsx'
import AdSlot from '../components/AdSlot.jsx'
import { markdownToCsv } from '../utils/parsers.js'

export default function TableToCsv() {
  const convert = useCallback((input) => {
    if (!input.trim()) {
      return ''
    }

    return markdownToCsv(input)
  }, [])

  return (
    <ToolLayout
      badge="Markdown → CSV"
      title="Markdown Table to CSV Converter"
      description="Convert Markdown tables from GitHub, Notion, ChatGPT and documentation into CSV for spreadsheets."
      seoTitle="Markdown Table to CSV Converter — Free Online Tool"
      seoDescription="Convert Markdown tables to CSV for Excel, Google Sheets and other spreadsheet apps. Handles escaped pipes and inconsistent Markdown tables."
    >
      <Converter
        inputLabel="Markdown table"
        outputLabel="CSV output"
        placeholder={`| Name | Age | City |
| --- | --- | --- |
| Manuel | 28 | Barcelona |
| Marta | 26 | Madrid |`}
        convertFn={convert}
        downloadExt="csv"
      />

      <AdSlot />

      <article
        className="card"
        style={{
          maxWidth: 760,
          margin: '32px auto 0'
        }}
      >
        <div style={{ padding: 24, lineHeight: 1.7 }}>
          <h2 className="h2" style={{ fontSize: 28 }}>
            Convert Markdown tables into CSV
          </h2>

          <p className="muted" style={{ marginTop: 12 }}>
            Markdown tables are excellent for documentation and AI workflows,
            but spreadsheets usually work better with CSV. This converter
            turns Markdown table data into CSV that can be imported into
            spreadsheet applications and other data tools.
          </p>

          <h3
            style={{
              marginTop: 24,
              fontWeight: 700,
              color: 'var(--ink)'
            }}
          >
            Useful for
          </h3>

          <ul
            className="muted"
            style={{
              marginTop: 10,
              paddingLeft: 20,
              display: 'grid',
              gap: 6
            }}
          >
            <li>GitHub and README tables</li>
            <li>Tables generated by ChatGPT and other AI tools</li>
            <li>Notion and documentation exports</li>
            <li>Data copied from Markdown files</li>
            <li>Moving table data into Excel or Google Sheets</li>
          </ul>

          <h3
            style={{
              marginTop: 24,
              fontWeight: 700,
              color: 'var(--ink)'
            }}
          >
            How it works
          </h3>

          <p className="muted" style={{ marginTop: 10 }}>
            Paste your Markdown table, check the generated CSV and use
            <strong> Copy</strong> or <strong>Download</strong> to continue
            working with the data.
          </p>

          <p className="muted" style={{ marginTop: 10 }}>
            The converter handles escaped pipe characters, different column
            widths and Markdown separator rows. Processing happens locally in
            your browser.
          </p>

          <div
            style={{
              marginTop: 24,
              paddingTop: 20,
              borderTop: '1px solid var(--line)'
            }}
          >
            <strong>Need to go the other way?</strong>

            <div
              style={{
                display: 'flex',
                gap: 12,
                flexWrap: 'wrap',
                marginTop: 12
              }}
            >
              <Link to="/csv-to-table" className="btn btn-ghost">
                CSV → Markdown
              </Link>

              <Link to="/text-to-table" className="btn btn-ghost">
                Text → Markdown
              </Link>

              <Link to="/cleaner" className="btn btn-ghost">
                Clean Markdown
              </Link>
            </div>
          </div>
        </div>
      </article>
    </ToolLayout>
  )
}
